### ISSUE TITLE
Expose Loggregator sinks

### ISSUE THREAD

**Issue by daviddawson** [cloudfoundry-incubator/lattice-release#103]
It would be great to expose setting up a logging sink in lattice.
So logging can be dumped out to papertrail, splunk etc.
Like the UPS setup in CF.

**Comment by dwelch2344** [comment]
+1 for this. Any eta on when this will be possible?

**Comment by amaltson** [comment]
:+1: here too, would be great to integrate this with our Logstash infrastructure.

**Comment by sclevine** [comment]
Lattice was a Cloud Foundry project focused on delivering the Diego application scheduler into the hands of users as quickly as possible before Diego was fully integrated to Cloud Foundry. Lattice served that purpose well, but now Diego is available as the application scheduler for Cloud Foundry, and Cloud Foundry is the best way to use Diego. Therefore, Lattice is no longer actively maintained.

Apologies for not addressing your issue.

-Stephen
