### ISSUE TITLE
Custom domains in routes

### ISSUE THREAD

**Issue by daviddawson** [cloudfoundry-incubator/lattice-release#104]
Currently all routes are subdomains on .xip.io.  

It would be good to support routes that are fully qualified.

**Comment by davidwadden** [comment]
So, assuming you have wildcard DNS resolution set up for *.some.sub.domain

this can be manually configured after finishing a terraform deploy:

SSH to the brain component (can lookup the IP via EC2 console)
```
ssh -i /path/to/ssh.key ubuntu@<BRAIN-HOST>
```

`su` up and edit `/var/lattice/setup/lattice-environment` as follows:
```
SYSTEM_DOMAIN=<PARENT_DOMAIN>
```
where from above example, `PARENT_DOMAIN=some.sub.domain`

then, restart the receptor and trafficcontroller as follows:
```
stop trafficcontroller;  start trafficcontroller
stop receptor; start receptor
```

**Comment by menicosia** [comment]
CC @MarkKropf looks like a similar issue to what we talked about yesterday.

**Comment by menicosia** [comment]
Hi @daviddawson I've gone ahead and created a Pivotal Tracker story for this issue: https://www.pivotaltracker.com/story/show/93628052

You can track our prioritization and progress there.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by davidwadden** [comment]
We're happy to announce [**v0.6.0**](https://github.com/cloudfoundry-incubator/lattice-release/releases/tag/v0.6.0) has released!  

Please take a look at the [ltc route documentation](http://lattice.cf/docs/ltc/#managing-multiple-ports) for more information about setting fully-qualified domain routes from `ltc`.

Let us know what you think!  If this doesn't meet your needs, please open a [new Github issue](https://github.com/cloudfoundry-incubator/lattice-release/issues/new).

@davidwadden
