### ISSUE TITLE
Docker Compose support

### ISSUE THREAD

**Issue by miguelpuyol** [cloudfoundry-incubator/lattice-release#136]
Running 1 container is great but running a bunch of them is awesome!

As docker compose is already a WIP, it would be great to provide support for this type of YAML based config within Lattice

**Comment by menicosia** [comment]
Hi @miguelpuyol,

We have spent a few days looking at this, and it looks like it may be possible. We have some other work that we'd like to do before spiking out how realistic Docker Compose support would be, so I am going to take the story generated above, and prioritize it appropriately in our backlog.

Feel free to snoop through the backlog to see how we've prioritized this, and do follow story [96452214](https://www.pivotaltracker.com/story/show/96452214) - that'll be the place where we either update with, "OK, this has been delivered," or ultimately, "Upon further consideration, we've decided this isn't something we intend to pursue."

Finally, as this is an open source project, do let us know if you're interested in working on this with us.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by sclevine** [comment]
Lattice was a Cloud Foundry project focused on delivering the Diego application scheduler into the hands of users as quickly as possible before Diego was fully integrated to Cloud Foundry. Lattice served that purpose well, but now Diego is available as the application scheduler for Cloud Foundry, and Cloud Foundry is the best way to use Diego. Therefore, Lattice is no longer actively maintained.

Apologies for not addressing your issue.

-Stephen
