### ISSUE TITLE
Multiple domain support

### ISSUE THREAD

**Issue by dwatrous** [cloudfoundry-incubator/lattice-release#137]
I would like to be able to share a lattice cluster among multiple websites. For example, suppose I had the following two domains:

flowercompany.com
deliverycompany.com

In cloudfoundry I can add these domains and assign a domain for each route to my application. I would like to be able to define routes for lattice applications in the same way.

The way lattice works right now, it is possible to specify a domain, but all applications deployed will be sub-domains of that top level domain. This would require multiple lattice deployments to accommodate my two domains above.

**Comment by menicosia** [comment]
Hi @dwatrous,

Just an update: As you see above, we've created a story in our project management system, Pivotal Tracker. It's how the PMs prioritize work on a project, and how we coordinate with the community. The Pivotal PMs also prioritize what the Pivotal engineering teams work on. In this case, while technically possible, it's going to be a bit of a research task. Since it's non-trivial effort, I'm going to prioritize the story after several other high priority stories in the Lattice backlog. That means that we'll get to it eventually, but it's not something the Eng team can work on immediately.

I'm also going to mark the story 'community,' as described in our [documentation](https://github.com/cloudfoundry-incubator/lattice#choosing-stories-from-our-tracker). I hope that perhaps someone enthusiastic enough can beat us to it. As always, we'll raise the priority of including a story in a release if there's a Pull Request waiting for review.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by dwatrous** [comment]
I'm happy to take a look at this if someone can give me a little
information first.

My understanding is that multiple domain support is already baked into
gorouter. The difficulty it seems would be around the lattice client and
startup scripts. The domains would need to be stored somewhere that the
gorouter could find them.

If an engineer could give me a little direction on this thread, I'll try to
find some time to take a look and submit a pull request.

Daniel

**Comment by svrc-pivotal** [comment]
@dwatrous bit late of an answer, but from what I can tell (i don't work on diego but I work with it with CF), you may be able to do this with the ltc client.   The lattice brain automatically pushes domain changes to the gorouter; the Receptor REST API already accepts routes from any hostname.    

The main bits that pick a single domain are in the ltc command line that always uses the system domain.  Code here:  https://github.com/cloudfoundry-incubator/lattice/blob/master/ltc/app_runner/app_runner.go#L294-297

A simple approach to the feature would be to allow an "ltc create" or "ltc update" command line option to override routes with FQDNs; and to add the functions to the various ltc areas.

**Comment by davidwadden** [comment]
@dwatrous 

This is currently in flight with #104 [[#93628052](https://www.pivotaltracker.com/story/show/93628052)].  We're implementing it a bit differently and wanted to confirm it met your needs.  We're also adding context path routing support with #217 [[#105301140](https://www.pivotaltracker.com/story/show/105301140)]. 

/cc @svrc-pivotal 

---
from [[#93628052](https://www.pivotaltracker.com/story/show/93628052)],

users should be able to specify domains other than the system domain in their routes

`--http-route=short-route:port`
`--http-route=long.route.other.domain:port`

if "short-route" contains a period, it's okay to assume this is a fqdn and we should not append the system domain

**Comment by dwatrous** [comment]
@davidwadden What I wanted to accomplish was to host sites with different domains on a single lattice installation. The way it is right now I am able to modify the domain, but all applications would have to be subdomains of that one top level domain.

**Comment by davidwadden** [comment]
Got it.  You'll have to bring-your-own DNS, but the upcoming version of the CLI will support specifying "long-form" routes (without the "system domain" appended), which should meet your needs.  We'll have a nightly build soon you can review to get feedback on.

**Comment by davidwadden** [comment]
We're happy to announce [**v0.6.0**](https://github.com/cloudfoundry-incubator/lattice-release/releases/tag/v0.6.0) has released!  

Please take a look at the [ltc route documentation](http://lattice.cf/docs/ltc/#managing-multiple-ports) for more information about setting fully-qualified domain routes from `ltc`.

Let us know what you think!  If this doesn't meet your needs, please open a [new Github issue](https://github.com/cloudfoundry-incubator/lattice-release/issues/new).

@davidwadden

**Comment by dwatrous** [comment]
@davidwadden I've just spun up a local lattice using Vagrant + virtualbox and confirmed that the routing accomplishes exactly what I need. It is quite flexible to define a full URL rather than defining a domain and then prepending the app name. In my view, this is preferable.
