### ISSUE TITLE
Informing clustered aws lattice of private docker registry (doesn't have to be secure)

### ISSUE THREAD

**Issue by sergueif** [cloudfoundry-incubator/lattice-release#145]
Hi I'm trying to setup a Lattice for internal apps within my org. So the networking is setup to totally shield lattice VPC within the company walls (no public ips or whatnot). Got me a vm running a private docker registry. Wanna tell the lattice about it. I did this

For every cell:
```
ssh ubuntu@private-ip-of-cell
sudo vi /etc/init/garden-linux.conf
# add the insecureDockerRegistryList="10.PRIVATE_IP:5000" line
sudo initctl stop garden-linux && sudo initctl start garden-linux
```

But that doesn't survive re-creating the vms of course, so I'd love a more declarative way. Maybe theres some way to parametrize the terraform stuff? or any other way of informing the cells of private registry.

**Comment by menicosia** [comment]
Hi @sergueif,

We have a story to automate a lot of the work described on the [private docker registries](https://github.com/cloudfoundry-incubator/lattice/blob/develop/docs/private-docker-registry.md) page in story #[92186438](https://www.pivotaltracker.com/story/show/92186438).

This work will include configuration of the Lattice cluster to reach a well-known location for a private docker registry.

OK to wait until we get to this feature? It's coming up after the current epic that we're working on.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by sergueif** [comment]
Yes, it can wait. I managed to get a private registry in by modifying the provisioning somewhat.

**Comment by sclevine** [comment]
Lattice was a Cloud Foundry project focused on delivering the Diego application scheduler into the hands of users as quickly as possible before Diego was fully integrated to Cloud Foundry. Lattice served that purpose well, but now Diego is available as the application scheduler for Cloud Foundry, and Cloud Foundry is the best way to use Diego. Therefore, Lattice is no longer actively maintained.

Apologies for not addressing your issue.

-Stephen
