### ISSUE TITLE
websocket: bad handshake error when creating a dockerized app

### ISSUE THREAD

**Issue by Klarzahs** [cloudfoundry-incubator/lattice-release#154]
Hello everybody.

I'm currently trying to set up a local test version of Lattice on my Windows Laptop, using Vagrant / VirtualBox.
EDIT: Vagrant version is 1.7.4
I pulled the v0.2.7 branch and "vagrant up" it, connected with putty, this part now works fine (I had to download the .tar.gz manually, following one of your answers to another issue). I set the LATTICE_SYSTEM_IP to 192.168.80.11.
I also created a vagrant file with the ubuntu/trusty64 image from the hashicorp server. Neither starting this vm nor installing *ltc* results in any problems. Connecting to the Lattice VM after configuring dnsmasq works:
    
     vagrant@vagrant-ubuntu-precise-64:~$ ltc target lattice.dev    
     Api Location Set 
As I'm in a corporate network with a proxy, I already set all the $http_proxy variables correctly to
    
    vagrant@vagrant-ubuntu-precise-64:~$ echo $http_proxy
    http://<user>:<pw>@<proyxy>:<port>
as discussed in issue [81](https://github.com/cloudfoundry-incubator/lattice/issues/81)
Our proxy also requires certain CA certificates. I was able to install and fix the Docker problems for that on a RHEL 7, basically adding the certificates. I did also add them to the ubuntu VM (in their respecting directory).
Now to my problem: whenever I want to run the *ltc test* or create an app (the cf/lattice-app) i get critical errors and the system is not able to run them, just add them to the list.
I'll add the error messages below, they're quite long.
Both test runs have the error message 
    
    dial tcp: lookup index.docker.io: no such host 
in them.
Creating apps result in 
    
    Error dialing traffic controller server: websocket: bad handshake.
    Please ask your ...
Running ltc list afterwards yields
    
    vagrant@vagrant-ubuntu-precise-64:~$ ltc list
    ------------------------------= Apps =-------------------------------
    App Name        Instances       DiskMB          MemoryMB        Route
    lattice         0/1             0               128             lattice.lattice.dev, lattice-8080.lattice.dev => 8080
    
    ------------------------------= Tasks =------------------------------
    No tasks to display.

I tried to install Docker on my Ubuntu Machine and connect to the hub there. The installation finished with no error, but when I try something like *docker pull ubuntu* I get a segmentation fault - is this related to using it in Vagrant?

I would be super glad if you have any suggestions, I'm stuck. If you need any further information I'd be happy to provide them, but be warned: I am not a Linux pro, so I might need the commands :)

Thanks 
Thomas

Here are the Error Logs (I cant add them through pastebin, sorry, its blocked)

------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------

vagrant@vagrant-ubuntu-precise-64:~$ ltc test
Running Suite: Lattice Integration Tests
========================================
Random Seed: 1438000051
Will run 2 of 2 specs

[test] Attempting to stream cluster debug logs
[test] Attempting to create lattice-test-app-7167b302-e51e-41a4-5e16-a9212229c632
[create] Error fetching image metadata: Get https://index.docker.io/v1/repositories/cloudfoundry/lattice-app/images: dial tcp: lookup index.docker.io: no such host[test] Attempting to remove app lattice-test-app-7167b302-e51e-41a4-5e16-a9212229c632
[remove] Removing lattice-test-app-7167b302-e51e-41a4-5e16-a9212229c632...
[remove] Error stopping lattice-test-app-7167b302-e51e-41a4-5e16-a9212229c632: lattice-test-app-7167b302-e51e-41a4-5e16-a9212229c632 is not started.
• Failure [0.159 seconds]
Lattice
/root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/integration_test/integration_test_runner.go:185
  docker
  /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/integration_test/integration_test_runner.go:132
    when desiring a docker-based LRP
    /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/integration_test/integration_test_runner.go:131
      eventually runs a docker app [It]
      /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/integration_test/integration_test_runner.go:124

      No future change is possible.  Bailing out early after 0.080s.
      Expected
          <int>: 15
      to match exit code:
          <int>: 0

      /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/integration_test/integration_test_runner.go:430
------------------------------
[test] Attempting to create lattice-test-app-cfa3e163-8414-4e78-433a-a4a641379be8
[create] Error fetching image metadata: Get https://index.docker.io/v1/repositories/cloudfoundry/lattice-app/images: dial tcp: lookup index.docker.io: no such host[test] Attempting to remove app lattice-test-app-cfa3e163-8414-4e78-433a-a4a641379be8
[remove] Removing lattice-test-app-cfa3e163-8414-4e78-433a-a4a641379be8...
[remove] Error stopping lattice-test-app-cfa3e163-8414-4e78-433a-a4a641379be8: lattice-test-app-cfa3e163-8414-4e78-433a-a4a641379be8 is not started.
• Failure [0.091 seconds]
Lattice
/root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/integration_test/integration_test_runner.go:185
  docker
  /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/integration_test/integration_test_runner.go:132
    when desiring a docker-based LRP
    /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/integration_test/integration_test_runner.go:131
      eventually runs a docker app with metadata from Docker Hub [It]
      /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/integration_test/integration_test_runner.go:130

      No future change is possible.  Bailing out early after 0.043s.
      Expected
          <int>: 15
      to match exit code:
          <int>: 0

      /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/integration_test/integration_test_runner.go:430
------------------------------

Summarizing 2 Failures:

[Fail] Lattice docker when desiring a docker-based LRP [It] eventually runs a docker app
/root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/integration_test/integration_test_runner.go:430

[Fail] Lattice docker when desiring a docker-based LRP [It] eventually runs a docker app with metadata from Docker Hub
/root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/integration_test/integration_test_runner.go:430

Ran 2 of 2 Specs in 0.263 seconds
FAIL! -- 0 Passed | 2 Failed | 0 Pending | 0 Skipped 

------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------

and for the create

vagrant@vagrant-ubuntu-precise-64:~$ ltc create lattice-app cloudfoundry/lattice-app
No port specified, image metadata did not contain exposed ports. Defaulting to 8080.
No working directory specified, using working directory from the image metadata...
Monitoring the app on port 8080...
No start command specified, using start command from the image metadata...
Start command is:
/lattice-app
Creating App: lattice-app
.Error dialing traffic controller server: websocket: bad handshake.
Please ask your Cloud Foundry Operator to check the platform configuration (traffic controller is ws://doppler.lattice.dev).
Error dialing traffic controller server: websocket: bad handshake.
Please ask your Cloud Foundry Operator to check the platform configuration (traffic controller is ws://doppler.lattice.dev).
.Error dialing traffic controller server: websocket: bad handshake.
Please ask your Cloud Foundry Operator to check the platform configuration (traffic controller is ws://doppler.lattice.dev).
Error dialing traffic controller server: websocket: bad handshake.
Please ask your Cloud Foundry Operator to check the platform configuration (traffic controller is ws://doppler.lattice.dev).
.Error dialing traffic controller server: websocket: bad handshake.
Please ask your Cloud Foundry Operator to check the platform configuration (traffic controller is ws://doppler.lattice.dev).
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x57ab68]

goroutine 30 [running]:
github.com/cloudfoundry-incubator/lattice/ltc/logs/console_tailed_logs_outputter.(*ConsoleTailedLogsOutputter).errorCallback(0xc20808c0c0, 0x0, 0x0)
        /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/logs/console_tailed_logs_outputter/console_tailed_logs_outputter.go:66 +0x28
github.com/cloudfoundry-incubator/lattice/ltc/logs/console_tailed_logs_outputter.*ConsoleTailedLogsOutputter.(github.com/cloudfoundry-incubator/lattice/ltc/logs/console_tailed_logs_outputter.errorCallback)·fm(0x0, 0x0)
        /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/logs/console_tailed_logs_outputter/console_tailed_logs_outputter.go:48 +0x3b
github.com/cloudfoundry-incubator/lattice/ltc/logs.(*logReader).readChannels(0xc20802b8e0, 0xc2082df0e0, 0xc2082df140, 0xc208287ac0, 0xc208287ad0)
        /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/logs/logs.go:42 +0xc1
github.com/cloudfoundry-incubator/lattice/ltc/logs.(*logReader).TailLogs(0xc20802b8e0, 0x7ffd7f2ba7a3, 0xb, 0xc208287ac0, 0xc208287ad0)
        /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/logs/logs.go:31 +0x108
created by github.com/cloudfoundry-incubator/lattice/ltc/logs/console_tailed_logs_outputter.(*ConsoleTailedLogsOutputter).OutputTailedLogs
        /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/logs/console_tailed_logs_outputter/console_tailed_logs_outputter.go:48 +0x122

goroutine 1 [chan receive]:
github.com/pivotal-golang/clock.(*realClock).Sleep(0xf516d0, 0x3b9aca00)
        /workspace/lattice/ltc/Godeps/_workspace/src/github.com/pivotal-golang/clock/clock.go:24 +0x73
github.com/cloudfoundry-incubator/lattice/ltc/app_runner/command_factory.(*AppRunnerCommandFactory).pollUntilSuccess(0xc208065360, 0x1bf08eb000, 0xc2081711d0, 0xc208287a01, 0x20)
        /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/app_runner/command_factory/app_runner_command_factory.go:320 +0x211
github.com/cloudfoundry-incubator/lattice/ltc/app_runner/command_factory.(*AppRunnerCommandFactory).pollUntilAllInstancesRunning(0xc208065360, 0x1bf08eb000, 0x7ffd7f2ba7a3, 0xb, 0x1, 0xa3f8d0, 0x5, 0x1a)
        /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/app_runner/command_factory/app_runner_command_factory.go:287 +0x91
github.com/cloudfoundry-incubator/lattice/ltc/app_runner/command_factory.(*AppRunnerCommandFactory).WaitForAppCreation(0xc208065360, 0x7ffd7f2ba7a3, 0xb, 0x1bf08eb000, 0x1, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/app_runner/command_factory/app_runner_command_factory.go:253 +0x1aa
github.com/cloudfoundry-incubator/lattice/ltc/docker_runner/command_factory.(*DockerRunnerCommandFactory).createApp(0xc208065360, 0xc2080bea80)
        /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/docker_runner/command_factory/docker_runner_command_factory.go:313 +0x19e6
github.com/cloudfoundry-incubator/lattice/ltc/docker_runner/command_factory.*DockerRunnerCommandFactory.(github.com/cloudfoundry-incubator/lattice/ltc/docker_runner/command_factory.createApp)·fm(0xc2080bea80)
        /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/docker_runner/command_factory/docker_runner_command_factory.go:162 +0x31
github.com/codegangsta/cli.Command.Run(0xa36d50, 0x6, 0x0, 0x0, 0xc2080b37f0, 0x1, 0x1, 0xaaa5b0, 0x1f, 0xb85f10, ...)
        /workspace/lattice/ltc/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:118 +0x1044
github.com/codegangsta/cli.(*App).Run(0xc20808a0f0, 0xc20800a000, 0x4, 0x4, 0x0, 0x0)
        /workspace/lattice/ltc/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:158 +0xd0c
main.main()
        /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/main.go:12 +0xa1

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [chan receive]:
github.com/cloudfoundry-incubator/lattice/ltc/exit_handler.(*exitHandler).Run(0xc20802c730)
        /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/exit_handler/exit_handler.go:36 +0x62
created by github.com/cloudfoundry-incubator/lattice/ltc/setup_cli.NewCliApp
        /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/setup_cli/setup_cli.go:28 +0x464

goroutine 29 [chan receive]:
github.com/cloudfoundry-incubator/lattice/ltc/logs/console_tailed_logs_outputter.(*ConsoleTailedLogsOutputter).OutputTailedLogs(0xc20808c0c0, 0x7ffd7f2ba7a3, 0xb)
        /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/logs/console_tailed_logs_outputter/console_tailed_logs_outputter.go:50 +0x16d
created by github.com/cloudfoundry-incubator/lattice/ltc/app_runner/command_factory.(*AppRunnerCommandFactory).WaitForAppCreation
        /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/app_runner/command_factory/app_runner_command_factory.go:250 +0x107

goroutine 10 [IO wait]:
net.(*pollDesc).Wait(0xc208011020, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208011020, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010fc0, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x7f0dca140d88, 0xc2080a7570)
        /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20803a138, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f0dca1430a0, 0xc20803a138, 0xc2080a0948, 0xc20800f000, 0x1000, 0x1000, 0x90d020, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc20806f320, 0xc20800f000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208055200)
        /usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208055200, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2080a08f0)
        /usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [select]:
net/http.(*persistConn).writeLoop(0xc2080a08f0)
        /usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 27 [IO wait]:
net.(*pollDesc).Wait(0xc208088f40, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208088f40, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208088ee0, 0xc2082e4000, 0x1000, 0x1000, 0x0, 0x7f0dca140d88, 0xc208276bc8)
        /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20803a1d8, 0xc2082e4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f0dca1430a0, 0xc20803a1d8, 0xc2080a0108, 0xc2082e4000, 0x1000, 0x1000, 0x90d020, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc208285d00, 0xc2082e4000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc2082dea80)
        /usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc2082dea80, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2080a00b0)
        /usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 28 [select]:
net/http.(*persistConn).writeLoop(0xc2080a00b0)
        /usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 33 [chan receive]:
github.com/cloudfoundry/noaa.func·003()
        /workspace/lattice/ltc/Godeps/_workspace/src/github.com/cloudfoundry/noaa/consumer.go:86 +0x87
created by github.com/cloudfoundry/noaa.(*Consumer).TailingLogsWithoutReconnect
        /workspace/lattice/ltc/Godeps/_workspace/src/github.com/cloudfoundry/noaa/consumer.go:91 +0x400

goroutine 35 [chan receive]:
github.com/cloudfoundry/noaa.func·003()
        /workspace/lattice/ltc/Godeps/_workspace/src/github.com/cloudfoundry/noaa/consumer.go:86 +0x87
created by github.com/cloudfoundry/noaa.(*Consumer).TailingLogsWithoutReconnect
        /workspace/lattice/ltc/Godeps/_workspace/src/github.com/cloudfoundry/noaa/consumer.go:91 +0x400

goroutine 37 [chan receive]:
github.com/cloudfoundry/noaa.func·003()
        /workspace/lattice/ltc/Godeps/_workspace/src/github.com/cloudfoundry/noaa/consumer.go:86 +0x87
created by github.com/cloudfoundry/noaa.(*Consumer).TailingLogsWithoutReconnect
        /workspace/lattice/ltc/Godeps/_workspace/src/github.com/cloudfoundry/noaa/consumer.go:91 +0x400

goroutine 39 [chan receive]:
github.com/cloudfoundry/noaa.func·003()
        /workspace/lattice/ltc/Godeps/_workspace/src/github.com/cloudfoundry/noaa/consumer.go:86 +0x87
created by github.com/cloudfoundry/noaa.(*Consumer).TailingLogsWithoutReconnect
        /workspace/lattice/ltc/Godeps/_workspace/src/github.com/cloudfoundry/noaa/consumer.go:91 +0x400

goroutine 41 [chan receive]:
github.com/cloudfoundry/noaa.func·003()
        /workspace/lattice/ltc/Godeps/_workspace/src/github.com/cloudfoundry/noaa/consumer.go:86 +0x87
created by github.com/cloudfoundry/noaa.(*Consumer).TailingLogsWithoutReconnect
        /workspace/lattice/ltc/Godeps/_workspace/src/github.com/cloudfoundry/noaa/consumer.go:91 +0x400
vagrant@vagrant-ubuntu-precise-64:~$

------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------

**Comment by menicosia** [comment]
Hi @Klarzahs,

Whoa, that's a very specific setup you have there.

As you know, although this is an Open Source (and therefore, community) project. We're really happy to see consistent interest in Windows! At Pivotal, we haven't gotten to start working on Windows support. I don't think there's a lot we can do about this until then. Right now, we can't even set up an environment to replicate your problems.

So I'm going to leave this GitHub issue open, here on the community project, and take the story that's in the Open Source tracker [[#99898902](https://www.pivotaltracker.com/story/show/99898902)], and align it with the Windows track we have planned.

If you haven't been able to sort out problems such as this by then, we should be able to take a look at that time.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by LaynePeng** [comment]
Hi, @Klarzahs , we met the same problem, do you have any update of this issue?

**Comment by sclevine** [comment]
Lattice was a Cloud Foundry project focused on delivering the Diego application scheduler into the hands of users as quickly as possible before Diego was fully integrated to Cloud Foundry. Lattice served that purpose well, but now Diego is available as the application scheduler for Cloud Foundry, and Cloud Foundry is the best way to use Diego. Therefore, Lattice is no longer actively maintained.

Apologies for not continuing to address this issue.

-Stephen
