### ISSUE TITLE
lattice Vagrant file not taking VM Memory & CORES environment variable.

### ISSUE THREAD

**Issue by saluru** [cloudfoundry-incubator/lattice-release#162]
when i'm bringing up vagrant vm locally, i set VM_MEMORY and VM_CORES, but vargrant configuration is not picking from environment variable, its calculating by total memory available on the hardware.

  cpus = `sysctl -n hw.ncpu`.to_i
      # sysctl returns Bytes and we need to convert to MB
      mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 4

**Comment by davidwadden** [comment]
We took a look at this, and it looks like `VM_MEMORY` and `VM_CORES` are not Vagrant-specific configurations, but seem to be used by bosh-lite configurations.  We found cloudfoundry/bosh-lite#191 which references these environment variables.

I've converted this to a feature request to support this functionality on our Pivotal Tracker at [[#100872484](https://www.pivotaltracker.com/story/show/100872484)].   In the meantime, you can edit the `Vagrantfile` manually to set the cluster CPU/Memory capacity.

Thanks!
David
