### ISSUE TITLE
vSphere cluster deployment

### ISSUE THREAD

**Issue by amaltson** [cloudfoundry-incubator/lattice-release#164]
I was wondering if there are any plans to add support for deploying Lattice on vSphere? [Terraform support seems to exist](/mevansam/terraform-provider-vsphere), although it doesn't seem to be [first class](/hashicorp/terraform/issues/102). Thanks.

**Comment by davidwadden** [comment]
@amaltson -

this was requested earlier in #98, we don't support automated installs to vsphere, but we have created a set of manual install [instructions](https://github.com/cloudfoundry-incubator/lattice/blob/master/docs/manual-install.md) that explains how to install Lattice without vagrant or terraform.

please take a look and let us know if you have any further questions!
@davidwadden  @crawsible

**Comment by teodor-pripoae** [comment]
Is there any instructions for deploying a lattice cluster manually ? I'm trying to setup a vagrant cluster for evaluation purposes, and I can't find a way to connect the virtual machines.

**Comment by menicosia** [comment]
Hi @teodor-pripoae,

No, we haven't written the clustered deploy doc yet. I've converted your bug into a feature request and placed it in the Documentation enhancements section of our backlog.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by amaltson** [comment]
@davidwadden sorry for the duplicate entry, I thought I had searched for it :disappointed:. As @teodor-pripoae pointed out, there aren't cluster deployment instructions which is really what I'm after. I'm fine without a Terraform script, but I'd like to set up a cluster.

From #98 
> Lattice will evolve into a developer on-ramp to Cloud Foundry

Which is actually exactly what I'm looking for. I want to get a Lattice up and running until we can get a CF in place. We use vSphere so I'd like the cluster setup there. Thanks again!

**Comment by menicosia** [comment]
@amaltson, @teodor-pripoae,

From looking at the `install-from-tar` script, I think it takes three different arguments:
> if [ $COMPONENT_TO_INSTALL != "cell" ] && [ $COMPONENT_TO_INSTALL != "brain" ] && [ $COMPONENT_TO_INSTALL != "collocated" ]; then

If this is something you want to push forward on before we've done formal documentation, I think it _may_ be as trivial as running with the argument `brain` on one VM, and `cell` on subsequent VMs.

/cc @davidwadden 

--
Marco Nicosia
Product Manager
Pivotal Software, Inc.

**Comment by teodor-pripoae** [comment]
Yes, but is there any setting required for cells to connect to a provided brain server ? Something like `BRAIN_URL=vm1.myapp.dev:8000` ?

**Comment by menicosia** [comment]
@teodor-pripoae,

I'm fairly sure if you set up the lattice-environment file, and correctly provide the Brain's IP wherever it shows `<system_ip>` the Cell will be able to connect to the Brain.

I am not sure if authentication will be needed; it may not be needed in the collocated context, but possibly in the clustered form.

--
Marco Nicosia
Product Manager
Pivotal Software, Inc.

**Comment by shakuzen** [comment]
:+1: for adding vSphere cluster support or at least documenting how to manually deploy a cluster.

**Comment by davidwadden** [comment]
Some update here.  There's activity over on hashicorp/terraform#3419 that looks promising.

We'll look into more closely once vmware support lands in [Terraform](https://terraform.io/)

**Comment by shinji62** [comment]
Oh that's nice :+1: for the vmware support

**Comment by sclevine** [comment]
Lattice was a Cloud Foundry project focused on delivering the Diego application scheduler into the hands of users as quickly as possible before Diego was fully integrated to Cloud Foundry. Lattice served that purpose well, but now Diego is available as the application scheduler for Cloud Foundry, and Cloud Foundry is the best way to use Diego. Therefore, Lattice is no longer actively maintained.

Apologies for not continuing to address this issue.

-Stephen
