### ISSUE TITLE
Problems deploying vagrant cluster, only first node runs tasks

### ISSUE THREAD

**Issue by teodor-pripoae** [cloudfoundry-incubator/lattice-release#177]
Hi,

I'm trying to simulate a 3 machine cluster using vagrant and it seems that only the first node is able to run apps.

My setup is as follows:

| machine   |    eth0         |    eth1       |     eth2        |
|---------------|-----------------|---------------|-----------------|
| c01           | 10.0.2.15       | 10.0.1.111    | 172.19.8.111      |
| c02           | 10.0.2.15       | 10.0.1.112    | 172.19.8.112      |
| c03           | 10.0.2.15       | 10.0.1.113    | 172.19.8.113      |

- eth0 - It is added by vagrant as NAT interface for controlling the vm
- eth1 - a bridged public ip, the vm will be accessible on the network, to simulate cloud public ip
- eth2 - a private network ip, this will be used as a private network between vms

Vagrant setup:

```ruby
(1..$compute_nodes).each do |i|
  hostname = "c%02d" % i
  public_ip = "10.0.1.#{i+110}"
  private_ip = "172.19.8.#{i+110}"

  config.vm.define hostname do |node|
    node.vm.box = "lattice/ubuntu-trusty-64"
    node.vm.box_version = '0.3.0'

    node.vm.provider "virtualbox" do |vb|
      vb.memory = $compute_memory
      vb.gui = false
    end

    node.vm.hostname = hostname

    node.vm.network "public_network", bridge: "en0", ip: public_ip
    node.vm.network "private_network", ip: private_ip

    # ... provisioning with chef solo
  end
end
```

Chef solo does the following:

- allow all trafic on eth2 subnet `sudo ufw allow from 172.19.8.0/24`
- deny all trafic on eth1
- creates /var/lattice/setup/lattice-environment for each node, see below
- downloads latest stable from s3
- for c01 runs `install-from-tar collocated`, for c02, c03 runs `install-from-tar cell`
- patches consul.json (see below) and then restarts consul agent

```bash
# C01
PUBLIC_IP=172.19.8.111
PRIVATE_IP=172.19.8.111
CONSUL_SERVER_IP=172.19.8.111
SYSTEM_IP=172.19.8.111
SYSTEM_DOMAIN=vag.kuende.cf
GARDEN_EXTERNAL_IP=172.19.8.111
LATTICE_CELL_ID=c01
# C02
PUBLIC_IP=172.19.8.112
PRIVATE_IP=172.19.8.112
CONSUL_SERVER_IP=172.19.8.111
SYSTEM_IP=172.19.8.111
SYSTEM_DOMAIN=vag.kuende.cf
GARDEN_EXTERNAL_IP=172.19.8.112
LATTICE_CELL_ID=c02
# C03
PUBLIC_IP=172.19.8.113
PRIVATE_IP=172.19.8.113
CONSUL_SERVER_IP=172.19.8.111
SYSTEM_IP=172.19.8.111
SYSTEM_DOMAIN=vag.kuende.cf
GARDEN_EXTERNAL_IP=172.19.8.113
LATTICE_CELL_ID=c03
```

Consul config patch:

```
# it was showing consul address as 10.0.2.15:8301 (eth0)
# and ltc visualize was showing only the first node
# this example is for c01, similar for c02, c03
{
    "advertise_addr": "172.19.8.111",
    "bind_addr": "172.19.8.111",
    "ports": {
        "dns": 53
    }
}
```

My domain `kuende.cf` is set for `vag` and `*.vag` to c01 ip (172.19.8.111).

```
$ ltc target vag.kuende.cf
Could not authenticate with the droplet store.

$ echo '{"target":"vag.kuende.cf","dav_blob_store":{"host": "vag.kuende.cf", "port": "8444"}}' > ~/.lattice/config.json

$ ltc target
Target:			vag.kuende.cf
Droplet store:	vag.kuende.cf:8444

$ ltc cells
Cells		Zone		Memory		Disk		Apps
c01			z1			2001M		8675M		0/0
c02			z1			2001M		8675M		0/0
c03			z1			2001M		8675M		0/0

$ ltc create lattice-app cloudfoundry/lattice-app

$ ltc visualize
Distribution
c01: •
c02: empty
c03: empty

$ ltc scale lattice-app 3
Scaling lattice-app to 3 instances
.....
App Scaled Successfully

$ ltc visualize
Distribution
c01: •••
c02: empty
c03: empty
```

**Comment by menicosia** [comment]
Hi @teodor-pripoae,

Is it very important that you deploy all three VMs on a single machine? The result that you are trying to achieve is comparable to what we do on the cloud (AWS, GCE, DO, ...) using Terraform. In fact, you are trying to convince scripts written in the Terraform context to work with Vagrant instead.

You may be able to make it work, but it's certainly not a use case we've planned for. Already, the Vagrant instance tries to take advantage of the physical resources on the host system - adding more Cells doesn't fundamentally mean you get more capacity than relying on the single Cell provided.

Finally, regarding the network customizations you are trying to implement: It may work, but it's entirely possible that the installation & configuration scripts make assumptions about which host:port combinations are expected to be open. There isn't any facility (yet) to specify which networks individual services should use for intra-cluster communication. Again, it's open source, so there's every chance you could modify Lattice to make this work, but it's not something that we've spent any time thinking about to date.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by teodor-pripoae** [comment]
Hi,

I've done a similar setup as digital ocean provides (the only difference is the eth0 which is added automatically by vagrant). 1 core for each vm, 2gb ram for each vm, 8gb disk for each vm, 1 public interface, 1 private interface.

I looked over terraform config for DO, and it seems that cell and brain are connected on [ipv4_address](https://www.terraform.io/docs/providers/do/r/droplet.html#ipv4_address), which is the public ipv4 address. Since DO is offering private networking for intra-datacenter traffic, I don't see why it should communicate on the public interface. Also becouse private network in DO is not actually a **private** network, but just a network **shared** with all the DO customers in that specific datacenter, firewall rules should be enforced there.

Just to make it clear, I'm using the same `install-from-tar` script that terraform is running, and providing the variables the same way that terraform is doing, but with chef. I think that the problem is due to lattice taking the first network interface available for clustering or ignoring firewall rules. I will do some more tests and I'll come later with an answer

**Comment by menicosia** [comment]
@teodor-pripoae,

Yes, I think you are right - Lattice does not expose a way to configure which networks to use for which communications.

It did occur to me to additionally make sure that you are aware that we've written a [manual install](https://github.com/cloudfoundry-incubator/lattice/blob/master/docs/manual-install.md) document. It may be helpful to you. It shows how we have constructed the various components to work together.

I don't think it'd be difficult to convince Lattice to listen on different IP addresses. I do see what you are saying about DO shared/private networks. So far, we haven't put a lot of security effort into Lattice, due to the fact that Lattice is meant to provision a Developer environment. Nonetheless, anything that's deployed to the cloud needs a certain minimum amount of security, so we are slowly introducing features intended to lock down the environments over time.

--
Marco Nicosia
Product Manager
Pivotal Software, Inc.
