### ISSUE TITLE
Cells disk is full

### ISSUE THREAD

**Issue by sergueif** [cloudfoundry-incubator/lattice-release#187]
Hi, it appears my cells ran out of disk space. I'm assuming it's mostly intermediate and old docker images I've been running. `du -a . | sort -nr | head` in `/var/lattice` shows `garden/graph` taking up lots of space. How can I clear old stuff to make room for the new?

**Comment by menicosia** [comment]
Hi @sergueif,

This is likely a deeper Diego issue; I've sent an inquiry to the Diego team to find out if there's already a standard way of dealing with this, and if not, is there a plan to do so?

--
Marco N. && David W.

**Comment by davidwadden** [comment]
In our upcoming release v0.6.0, we're bumping [garden-linux]() to **v.307.0**, which includes cloudfoundry-incubator/garden-linux-release#7.  This should more aggressively garbage collect layers following container shutdown.

**Comment by davidwadden** [comment]
We've made our **v0.6.0** release build (not yet published on github), which now includes "garbage collection" of docker layers after apps have stopped.   Please take a look at http://lattice.s3.amazonaws.com/nightly/lattice-bundle-v0.6.0.zip. Getting `ltc` is a bit different - it's now hosted by the cluster itself and instructions for downloading are at https://github.com/cloudfoundry-incubator/lattice-release#install-the-lattice-cli.  The website will be updated shortly to reflect the changes as well.
