### ISSUE TITLE
Deploy Lattice into existing VPC

### ISSUE THREAD

**Issue by vishalmaheswari** [cloudfoundry-incubator/lattice-release#193]
terraform get -update
Get: git::https://github.com/cloudfoundry-incubator/lattice.git?ref=v0.3.0 (update)
Error loading Terraform: Error downloading modules: error downloading module 'https://github.com/cloudfoundry-incubator/lattice.git?ref=v0.3.0': /usr/local/git/bin/git exited with 128: fatal: could not create leading directories of '.terraform/modules/090ee6929064717ffcf3e9f437dcb25d': Permission denied

I also tried it with sudo.

sudo terraform get -update
sudo: terraform: command not found

**Comment by davidwadden** [comment]
hey, sorry for the delay getting back to you!

`terraform` attempts to clone in the lattice repo behind the scenes, so the user that runs terraform needs to have write privileges to the current folder (containing the `lattice.<platform>.tf` 

couple things:
1) try our latest release - [**v0.4.0**](https://github.com/cloudfoundry-incubator/lattice/releases/tag/v0.4.0)
2) follow the [instructions](https://github.com/cloudfoundry-incubator/lattice#clustered-deployment) to work with our new bundles

if you continue to have issues, please provide a file listing `ls -l` where you're running terraform from, and anything else looks helpful to identify the permissions issue.

the error above looks like `terraform` is in a location that does not reside in root user's `PATH`, but we don't recommend resorting to `sudo` to resolve this error.

**Comment by vishalmaheswari** [comment]
Hi David.

Thanks for your response. I just realized my keys were not working properly. Now that it is working I will tell you my use case. I want to deploy Cloud Foundry on an existing VPC in an existing subnet.

When I executed terrafrom apply below is the output i received.

/opt/data2/terraform >terraform apply
aws_instance.example: Creating...
  ami:                      "" => "ami-408c7f28"
  availability_zone:        "" => "<computed>"
  ebs_block_device.#:       "" => "<computed>"
  ephemeral_block_device.#: "" => "<computed>"
  instance_type:            "" => "t1.micro"
  key_name:                 "" => "<computed>"
  placement_group:          "" => "<computed>"
  private_dns:              "" => "<computed>"
  private_ip:               "" => "<computed>"
  public_dns:               "" => "<computed>"
  public_ip:                "" => "<computed>"
  root_block_device.#:      "" => "<computed>"
  security_groups.#:        "" => "<computed>"
  source_dest_check:        "" => "1"
  subnet_id:                "" => "<computed>"
  tenancy:                  "" => "<computed>"
  vpc_security_group_ids.#: "" => "<computed>"
module.lattice-aws.aws_vpc.lattice-network: Creating...
  cidr_block:                "" => "10.227.224.0/19"
  default_network_acl_id:    "" => "<computed>"
  default_security_group_id: "" => "<computed>"
  dhcp_options_id:           "" => "<computed>"
  enable_dns_hostnames:      "" => "1"
  enable_dns_support:        "" => "1"
  main_route_table_id:       "" => "<computed>"
  tags.#:                    "" => "1"
  tags.Name:                 "" => "lattice"
Error applying plan:

2 error(s) occurred:

* aws_vpc.lattice-network: Error creating VPC: UnauthorizedOperation: You are not authorized to perform this operation.
        status code: 403, request id: []
* aws_instance.example: Error launching source instance: MissingInput: No subnets found for the default VPC 'vpc-c00af0a5'. Please specify a subnet.
        status code: 400, request id: []

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


Moreover, I would want to deploy cloud foundry  for microsite automation in an existing subnet of a VPC. That means my AWS infrastructure is set up. Just deploy Cloud Foundry in my existing infrastructure of VPC and subnet. 

So will that be possible.? 

Your help would be appreciated.


Thanks a lot in advance.

**Comment by svrc-pivotal** [comment]
@vishalmaheswari This is possible my modifying the terraform `resource.tf` to remove all the resources you don't need Terraform to manage and adding variables for the resources you already have.    

An example of this is here:  svrc-pivotal/lattice@dd58372c553cf4c806c28351626de63fb87e0184

Note that Terraform would have to at the very least provision your instances and Elastic IP.   If you want an even more custom setup, there is a manual install http://lattice.cf/docs/manual-install/

Finally, if you want to install full Cloud Foundry (not Lattice) on an existing VPC, you would use BOSH , which will respect your existing VPC/Subnet, with docs here http://docs.cloudfoundry.org/deploying/

**Comment by davidwadden** [comment]
@vishalmaheswari we have some stories coming up that will support the vagrant-aws plugin to deploy a single collocated vm to your default vpc [[#105376966](https://www.pivotaltracker.com/story/show/105376966)] [[#104756750](https://www.pivotaltracker.com/story/show/104756750)].  then that can be coupled with [mitchellh/vagrant-aws](https://github.com/mitchellh/vagrant-aws#configuration) to place that vm in an existing vpc.
