### ISSUE TITLE
cli fails with go 1.5.x

### ISSUE THREAD

**Issue by rahulkj** [cloudfoundry-incubator/lattice-release#201]
> go get -d github.com/cloudfoundry-incubator/lattice/ltc
```
package github.com/docker/docker/nat: cannot find package "github.com/docker/docker/nat" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/github.com/docker/docker/nat (from $GOROOT)
	/Users/<username>/go/src/github.com/docker/docker/nat (from $GOPATH)
```

I tried cleaning my pkg and trying to `godep restore`.. still no luck. Does the CLI work with go 1.5.x?

**Comment by davidwadden** [comment]
The `ltc` CLI should work with Go 1.5.1 (at least) - Check our [TravisCI](https://travis-ci.org/cloudfoundry-incubator/lattice/builds/81485108) out.  However, the Lattice cluster is only supported against go1.4, there's a fair number of changes that need to be made to support go1.5 there.

Our official development environment is described at: https://github.com/cloudfoundry-incubator/lattice/tree/master/development

Another way to make it work without `godep restore` is to tweak your `GOPATH`, similar to how we do in https://github.com/cloudfoundry-incubator/lattice/blob/master/.travis.yml

I haven't specifically tested the `godep restore` flow on go1.5, though.  See if any of these alternatives meet your needs, and if not, I can see if there's something up with `godep restore` + go1.5

**Comment by davidwadden** [comment]
We're now managing our `ltc` dependencies using submodules from [lattice-release](https://github.com/cloudfoundry-incubator/lattice-release).  If you use [`direnv`](http://direnv.net/) to set up the environment variables, `ltc` should just work after you:

```bash
$ git clone https://github.com/cloudfoundry-incubator/lattice-release --recursive
$ cd lattice-release
$ git submodule update --init --recursive
$ go install github.com/cloudfoundry-incubator/ltc
```

Let us know if that works for you
