### ISSUE TITLE
Container rebalancing problem

### ISSUE THREAD

**Issue by lexsys27** [cloudfoundry-incubator/lattice-release#206]
<img width="418" alt="screen shot 2015-09-25 at 13 33 17" src="https://cloud.githubusercontent.com/assets/9861024/10098549/da2bd5cc-638a-11e5-8cf9-f41294229306.png">

After start/stop cell-1 all containers reside on cell-0 and are not moved to cell-1 by converger. I expect diego to redistribute containers equally between cells, as if cell-0 dies we have downtime though a number of containers is running and there is healthy cell available.

**Comment by onsi** [comment]
We don't do any dynamic rebalancing (yet).  This is on the roadmap but not a very high priority at this point.

**Comment by shakuzen** [comment]
As a manual workaround gleaned from Matt Stine's talk at SpringOne, if you scale the app after cell-1 comes back up, all cells will be used.

**Comment by lexsys27** [comment]
Thank you for answers!
