### ISSUE TITLE
Manual Install Instructions Missing Requirement

### ISSUE THREAD

**Issue by mcowger** [cloudfoundry-incubator/lattice-release#212]
The manual install instructions fail to list a required component (`jq`).

**Comment by sclevine** [comment]
Lattice was a Cloud Foundry project focused on delivering the Diego application scheduler into the hands of users as quickly as possible before Diego was fully integrated to Cloud Foundry. Lattice served that purpose well, but now Diego is available as the application scheduler for Cloud Foundry, and Cloud Foundry is the best way to use Diego. Therefore, Lattice is no longer actively maintained.

Apologies for not addressing your issue.

-Stephen
