### ISSUE TITLE
Manual Install Instructions Include Incorrect Directory

### ISSUE THREAD

**Issue by mcowger** [cloudfoundry-incubator/lattice-release#213]
Step 4 includes an instruction to perform:

`sudo tar -xzf /tmp/cflinuxfs2-<STACK_VERSION>.tar.gz -C /var/lattice/rootfs/cflinuxfs2`

but it should be:

`sudo tar -xzf /tmp/cflinuxfs2-<STACK_VERSION>.tar.gz -C /var/lattice-image/rootfs/cflinuxfs2`

**Comment by mcowger** [comment]
Note - I'd submit PRs for both this and #212, but the docs dont appear to be on github.

**Comment by explody** [comment]
+1 on this.  Though, I'd perhaps take a different angle - just remove the lines referencing /var/lattice-image from install-from-tar since the directory creation and tarball extraction are covered in the manual instructions anyway.  The script works given this patch:

```
--- install-from-tar.orig	2015-11-28 20:23:57.359930419 +0000
+++ install-from-tar	2015-11-28 20:24:10.445384251 +0000
@@ -30,11 +30,6 @@
     cp /tmp/lattice-build/common/webdav/lighttpd.conf-auth-disabled /etc/lighttpd/lighttpd.conf
 fi

-echo "Installing cflinuxfs2 rootfs..."
-mkdir -p /var/lattice/rootfs
-mv /var/lattice-image/rootfs/cflinuxfs2 /var/lattice/rootfs
-echo "done"
-
 /etc/init.d/lighttpd start

 sleep 1
```

**Comment by sclevine** [comment]
Lattice was a Cloud Foundry project focused on delivering the Diego application scheduler into the hands of users as quickly as possible before Diego was fully integrated to Cloud Foundry. Lattice served that purpose well, but now Diego is available as the application scheduler for Cloud Foundry, and Cloud Foundry is the best way to use Diego. Therefore, Lattice is no longer actively maintained.

Apologies for not addressing your issue.

-Stephen
