### ISSUE TITLE
Use of context path routes with Lattice

### ISSUE THREAD

**Issue by davidwadden** [cloudfoundry-incubator/lattice-release#217]
Submitted via cf-lattice mailing list.

---------- Forwarded message ---------
From: Casey Hadden <me@caseyhadden.com>
Date: Mon, Oct 5, 2015 at 7:46 AM
Subject: [cf-lattice] use of context path routes with Lattice
To: <cf-lattice@lists.cloudfoundry.org>

Hi all,

We've been experimenting with the new context path based routing feature in a full Cloud Foundry environment. We're interested in trying the same thing within Lattice. Based on the available information, it looks like the same router is being used in both environments, so I'm expecting the capability is there at that level. However, it looks like there is no ability to provide a path instead of a host via the ltc command line or the receptor API.

Is that accurate or am I missing something to make the context path based routing work in Lattice?
Has anyone traveled this path before?
Is it something that could be done with some work to the various components or something that will never work in the Lattice environment?

Thanks.
Casey

**Comment by davidwadden** [comment]
@shalako Can you let us know whether gorouter supports this?  And if so, any resources that are doing this today?  (e.g., CF CLI, API with Diego)

**Comment by shalako** [comment]
Gorouter already supports this. If the hostname in the `cf-router` section of the create/update lrp call includes a path, Gorouter will route requests for that url to associated backends.

```
"routes": {
        "cf-router": [
            {
                "hostnames": ["a.example.com/somepath"],
                "port": 8080
            }
        ]
    }
```

**Comment by caseyhadden** [comment]
Thanks, @shalako.

FWIW, I was able to get this working in lattice v0.5.0. I made a very much oversimplified and hack change in the ltc command line tool:

``` go
		hostname := ""
		if (strings.Contains(override.HostnamePrefix, appRunner.systemDomain)) {
			hostname = override.HostnamePrefix
		} else {
			hostname = fmt.Sprintf("%s.%s", override.HostnamePrefix, appRunner.systemDomain)
		}
		routeMap[override.Port] = append(routeMap[override.Port], hostname)
		//routeMap[override.Port] = append(routeMap[override.Port], fmt.Sprintf("%s.%s", override.HostnamePrefix, appRunner.systemDomain))
```	

That let me issue 'ltc create --http-routes=192.168.11.11.xip.io/foo foo foo-docker-image' and then I'm able to access 192.168.11.11.xip.io/foo and have the correct application respond.

**Comment by davidwadden** [comment]
We're happy to announce [**v0.6.0**](https://github.com/cloudfoundry-incubator/lattice-release/releases/tag/v0.6.0) has released!  

Please take a look at the [ltc route documentation](http://lattice.cf/docs/ltc/#managing-multiple-ports) for more information about setting context path routes from `ltc`.

Let us know what you think!  If this doesn't meet your needs, please open a [new Github issue](https://github.com/cloudfoundry-incubator/lattice-release/issues/new).

@davidwadden
