### ISSUE TITLE
Virtualbox 5.0 not supported

### ISSUE THREAD

**Issue by mikegehard** [cloudfoundry-incubator/lattice-release#220]
The latest Docker Toolbox installs Virtualbox 5.0 so when I go to start up Lattice 0.5.0 after installing Docker toolbox, I get the following error:

```
Vagrant has detected that you have a version of VirtualBox installed
that is not supported. Please install one of the supported versions
listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3
```

**Comment by sclevine** [comment]
Hey @mikegehard,

What version of Vagrant do you have installed? I believe 1.7.3 is necessary to run Virtualbox 5.

It might also be worth noting that we're releasing Lattice 0.6.0 (which comes with the Virtualbox 5 guest additions and has more stable cluster components) later this week.

**Comment by mikegehard** [comment]
Thanks for the quick response.

I am running Vagrant 1.5.4 so it looks like I may be out of date. It makes
sense that Vagrant would be giving me that error and not Lattice. Was a bit
shocked so my knee jerk reaction was to blame Lattice. :-)

I'll work on a pull request for the README (unless you have another place
for it) that let's people know about the issue.

Looking forward to Lattice 0.6.0.

**Comment by mikegehard** [comment]
See #221

**Comment by davidwadden** [comment]
Thanks for submitting this PR, sorry for the confusion around the merge.  The **v0.6.0** build is brand new but hasn't been published yet on Github.  Take a look!  It's available for download at http://lattice.s3.amazonaws.com/nightly/lattice-bundle-v0.6.0.zip and instructions for getting the CLI served by the cluster are at https://github.com/cloudfoundry-incubator/lattice-release#install-the-lattice-cli.

I'm gonna close this issue as the website change should address this with **v0.6.0**.

@davidwadden
