### ISSUE TITLE
Installing Lattice using Terraform on AWS hangs

### ISSUE THREAD

**Issue by smcgregor83** [cloudfoundry-incubator/lattice-release#222]
I am currently trying to follow the installation guide here - https://github.com/cloudfoundry-incubator/lattice/tree/master/terraform/aws but I am running into problems. The Lattice Brain gets created on my AWS account but then the installation process spins for a while before ultimately giving up.

While spinning, the following is repeated in the logs approximately every 5 seconds:

2015/10/20 01:19:46 [DEBUG] vertex module.lattice-aws.aws_eip.ip, waiting for: module.lattice-aws.aws_instance.lattice-brain
2015/10/20 01:19:46 [DEBUG] vertex provider.module.lattice-aws.aws (close), waiting for: module.lattice-aws.aws_instance.cell
2015/10/20 01:19:46 [DEBUG] vertex provisioner.module.lattice-aws.remote-exec (close), waiting for: module.lattice-aws.aws_instance.cell
2015/10/20 01:19:46 [DEBUG] vertex provisioner.module.lattice-aws.local-exec (close), waiting for: module.lattice-aws.aws_instance.cell
2015/10/20 01:19:46 [DEBUG] vertex module.lattice-aws.output.lattice_target, waiting for: module.lattice-aws.aws_eip.ip
2015/10/20 01:19:46 [DEBUG] vertex provisioner.module.lattice-aws.file (close), waiting for: module.lattice-aws.aws_instance.cell
2015/10/20 01:19:46 [DEBUG] vertex output.lattice_target, waiting for: module.lattice-aws.output.lattice_target
2015/10/20 01:19:46 [DEBUG] vertex module.lattice-aws.aws_instance.cell, waiting for: module.lattice-aws.aws_eip.ip
2015/10/20 01:19:46 [DEBUG] vertex root, waiting for: provisioner.module.lattice-aws.local-exec (close)

This continues for maybe 20 minutes before terminating with the following:

2015/10/20 01:35:32 [DEBUG] root.lattice-aws: eval: *terraform.EvalIf
2015/10/20 01:35:32 [DEBUG] root.lattice-aws: eval: *terraform.EvalWriteDiff
2015/10/20 01:35:32 [DEBUG] root.lattice-aws: eval: *terraform.EvalIf
2015/10/20 01:35:32 [DEBUG] root.lattice-aws: eval: *terraform.EvalSequence
2015/10/20 01:35:32 [DEBUG] root.lattice-aws: eval: *terraform.EvalWriteStateTainted
2015/10/20 01:35:32 [DEBUG] root.lattice-aws: eval: *terraform.EvalIf
2015/10/20 01:35:32 [DEBUG] root.lattice-aws: eval: *terraform.EvalClearPrimaryState
2015/10/20 01:35:32 [DEBUG] root.lattice-aws: eval: *terraform.EvalApplyPost
2015/10/20 01:35:32 [ERROR] root.lattice-aws: eval: *terraform.EvalApplyPost, err: 1 error(                                                                                                  s) occurred:

* Upload failed: write tcp 52.91.167.71:22: connection timed out
2015/10/20 01:35:32 [ERROR] root.lattice-aws: eval: *terraform.EvalSequence, err: 1 error(s                                                                                                  ) occurred:

* Upload failed: write tcp 52.91.167.71:22: connection timed out
2015/10/20 01:35:32 [ERROR] root.lattice-aws: eval: *terraform.EvalOpFilter, err: 1 error(s                                                                                                  ) occurred:

* Upload failed: write tcp 52.91.167.71:22: connection timed out
2015/10/20 01:35:32 [ERROR] root.lattice-aws: eval: *terraform.EvalSequence, err: 1 error(s                                                                                                  ) occurred:

* Upload failed: write tcp 52.91.167.71:22: connection timed out
Error applying plan:

1 error(s) occurred:

* Upload failed: write tcp 52.91.167.71:22: connection timed out

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
2015/10/20 01:35:32 [DEBUG] vertex module.lattice-aws.aws_eip.ip, got dep: module.lattice-a                                                                                                  ws.aws_instance.lattice-brain
2015/10/20 01:35:32 [DEBUG] vertex module.lattice-aws.output.lattice_target, got dep: modul                                                                                                  e.lattice-aws.aws_eip.ip
2015/10/20 01:35:32 [DEBUG] vertex module.lattice-aws.aws_instance.cell, got dep: module.la                                                                                                  ttice-aws.aws_eip.ip
2015/10/20 01:35:32 [DEBUG] vertex module.lattice-aws.aws_instance.cell, got dep: module.la                                                                                                  ttice-aws.aws_instance.cell (destroy)
2015/10/20 01:35:32 [DEBUG] vertex output.lattice_target, got dep: module.lattice-aws.outpu                                                                                                  t.lattice_target
2015/10/20 01:35:32 [DEBUG] vertex provider.module.lattice-aws.aws (close), got dep: module                                                                                                  .lattice-aws.aws_instance.cell
2015/10/20 01:35:32 [DEBUG] vertex provider.module.lattice-aws.aws (close), got dep: module                                                                                                  .lattice-aws.aws_route_table_association.lattice-network
2015/10/20 01:35:32 [DEBUG] vertex provisioner.module.lattice-aws.remote-exec (close), got                                                                                                   dep: module.lattice-aws.aws_instance.cell
2015/10/20 01:35:32 [DEBUG] vertex provisioner.module.lattice-aws.local-exec (close), got d                                                                                                  ep: module.lattice-aws.aws_instance.cell
2015/10/20 01:35:32 [DEBUG] vertex provisioner.module.lattice-aws.file (close), got dep: mo                                                                                                  dule.lattice-aws.aws_instance.cell
2015/10/20 01:35:32 [DEBUG] vertex root, got dep: provisioner.module.lattice-aws.local-exec                                                                                                   (close)
2015/10/20 01:35:32 [DEBUG] vertex root, got dep: provisioner.local-exec (close)
2015/10/20 01:35:32 [DEBUG] vertex root, got dep: provisioner.module.lattice-aws.file (clos                                                                                                  e)
2015/10/20 01:35:32 [DEBUG] vertex root, got dep: module.lattice-aws.provisioner.chef
2015/10/20 01:35:32 [DEBUG] vertex root, got dep: provisioner.file
2015/10/20 01:35:32 [DEBUG] vertex root, got dep: provisioner.remote-exec
2015/10/20 01:35:32 [DEBUG] vertex root, got dep: provider.module.lattice-aws.aws (close)
2015/10/20 01:35:32 [DEBUG] vertex root, got dep: provisioner.module.lattice-aws.remote-exe                                                                                                  c (close)
2015/10/20 01:35:32 [DEBUG] vertex root, got dep: provisioner.remote-exec (close)
2015/10/20 01:35:32 [DEBUG] vertex root, got dep: output.lattice_password
2015/10/20 01:35:32 [DEBUG] vertex root, got dep: provisioner.chef
2015/10/20 01:35:32 [DEBUG] vertex root, got dep: module.lattice-aws.plan-destroy
2015/10/20 01:35:32 [DEBUG] vertex root, got dep: provisioner.file (close)
2015/10/20 01:35:32 [DEBUG] vertex root, got dep: output.lattice_target
2015/10/20 01:35:32 [DEBUG] vertex root, got dep: output.lattice_username
2015/10/20 01:35:32 [DEBUG] waiting for all plugin processes to complete...
2015/10/20 01:35:32 [DEBUG] /opt/ke/prototypes/lattice/terraform/terraform-provisioner-chef                                                                                                  
: plugin process exited
2015/10/20 01:35:32 [DEBUG] /opt/ke/prototypes/lattice/terraform/terraform-provisioner-file                                                                                                  : plugin process exited
2015/10/20 01:35:32 [DEBUG] /opt/ke/prototypes/lattice/terraform/terraform-provider-aws: plugin process exited
2015/10/20 01:35:32 [DEBUG] /opt/ke/prototypes/lattice/terraform/terraform-provisioner-remote-exec: plugin process exited
2015/10/20 01:35:32 [DEBUG] /opt/ke/prototypes/lattice/terraform/terraform-provisioner-local-exec: plugin process exited

Now this might be as simple as increasing timeout periods somewhere, but I wanted to seek advice on the best way to proceed.

**Comment by smcgregor83** [comment]
Sorry I should have mentioned I have tried both Lattice 0.5.0 and 0.4.4 using Terraform 0.6.4.

**Comment by davidwadden** [comment]
This looks something networky attempting to copy up the `lattice.tgz` locally.

Do you have any special network restrictions on your local computer / network?  Terraform should be creating its own VPC and setting its own ingress rules, so I don't think this is on the cluster side.

**Comment by mdelillo** [comment]
We've have a new pre-release version of lattice [here](https://lattice.s3.amazonaws.com/releases/lattice-bundle-v0.6.0.zip), does upgrading to that version fix your issue?
