### ISSUE TITLE
unable to install LTC CLI

### ISSUE THREAD

**Issue by mehiar** [cloudfoundry-incubator/lattice-release#231]
Hi,

It seems that the URL for installing LTC CLI using the following command for linux is no longer working:
"curl -O http://receptor.local.lattice.cf/v1/sync/linux/ltc"

I was wondering if there is another way to get LTC installed.

Thank you,
Mehiar

**Comment by davidwadden** [comment]
What version Lattice are you using?

Is this vagrant or terraform?  Are you setting the IP to anything beside default?

**Comment by mehiar** [comment]
I am running lattice on terraform. I am not changing any default values. I am also able to use curl to get other links so this should not be a networking issue.

**Comment by davidwadden** [comment]
`local.lattice.cf` is pinned to 192.168.11.11, the default IP address for vagrant.

If you're using terraform, you need to replace "local.lattice.cf" with `$(terraform output target).xip.io` 

See: 
* http://lattice.cf/docs/terraform/#2-download-compatible-ltc 
* https://github.com/cloudfoundry-incubator/lattice-release#aws-terraform-install

**Comment by mehiar** [comment]
Thanks. This is now working.
