### ISSUE TITLE
Getting WARNING on ltc target

### ISSUE THREAD

**Issue by trisberg** [cloudfoundry-incubator/lattice-release#234]
I'm running latest 0.6.0 release and getting WARNING message whenever I execute a target command. I believe my `ltc` command is the latest and I even did `ltc sync`.

```
$ ltc -v
ltc version v0.6.0-34-g32acfa9 (diego 0.1434.0)
$ ltc sync
Updated ltc to the latest version.
$ ltc target local.lattice.cf
WARNING: local ltc version (v0.6.0-34-g32acfa9) does not match target expected version.
Run `ltc sync` to replace your local ltc command-line tool with your target cluster's expected version.
API location set.
```

**Comment by keaty** [comment]
Thanks for reporting this. The fix will be included in the next release, but you can download the [latest nightly build](https://lattice.s3.amazonaws.com/nightly/lattice-bundle-v0.6.0-81-g6d6dfb8.zip) to get it now.

**Comment by davidwadden** [comment]
Closing issue.  This fix is available in our [nightlies](https://lattice.s3.amazonaws.com/nightly/index.html) and will land in **v0.7.0**, expected shortly.

Thanks again!
David
