### ISSUE TITLE
Trouble simply downloading ltc from cluster - Manjaro linux

### ISSUE THREAD

**Issue by dshuck** [cloudfoundry-incubator/lattice-release#237]
I am simply following the getting started guide here: http://lattice.cf/docs/getting-started/ and have remained hung up on something that I don't see any other mention of.    I get all the way through the process where vagrant up completes successfully and see:
```
==> default: Waiting for services to start...
==> default: Lattice is now installed and running.
==> default: ----------------------------------------------------------------
==> default: To obtain a version of ltc that is compatible with your cluster:
==> default: $ curl -O http://receptor.local.lattice.cf/v1/sync/linux/ltc
==> default: $ chmod +x ltc
==> default: Optionally, move ltc to a directory in your PATH.
==> default: You may then target your cluster using: ltc target local.lattice.cf
==> default: ----------------------------------------------------------------
```

I then do the curl operation to download ltc and get:
```
curl -O http://receptor.local.lattice.cf/v1/sync/linux/ltc 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:07 --:--:--     0curl: (7) Failed to connect to receptor.local.lattice.cf
```
And trying wget, it appears that I get the same connection timeout...
```
wget http://receptor.local.lattice.cf/v1/sync/linux/ltc 
--2015-11-28 11:59:03--  http://receptor.local.lattice.cf/v1/sync/linux/ltc
Resolving receptor.local.lattice.cf (receptor.local.lattice.cf)... 192.168.11.11
Connecting to receptor.local.lattice.cf (receptor.local.lattice.cf)|192.168.11.11|:80... failed: Connection timed out.
Retrying.
```

I was wondering if the cluster is truly up, so I ran 
```
vboxmanage list runningvms
``` 
and see....
```
"vagrant_default_1448435783935_53895" {a2aa046c-a9ec-44cb-a83b-228126ed103f}
```
...which tells me that it is running.  Does anyone have any suggestions for moving forward?  I have been stuck here for far too long!

**Comment by dshuck** [comment]
As a followup, I have found a solution.  I had to open the VirtualBox GUI, go into the network settings for the vagrant instance, and modify "Promiscuous Mode" to "Allow VMs" as you can see in the image below.  I am going to leave this bug open in case that is perhaps a modification that the developers need to add so that it does this by default.  If not, feel free to close it.
![Screenshot of settings](http://i.imgur.com/CSDFW2e.png)

**Comment by philipz** [comment]
@dshuck, it's work! Thank you.
