### ISSUE TITLE
Documentation for using a private Docker registry with Lattice 0.6.0

### ISSUE THREAD

**Issue by chadmaughan** [cloudfoundry-incubator/lattice-release#238]
Starting with the 0.5.0 release's documentation as a general guideline for the steps needed to access a private Docker registry (see http://lattice.cf/docs/private-docker-registry/), I attempted to dive into the garden-linux included with the 0.6.0 Lattice release.  I quickly realized I'm woefully ignorant of all the internals of the different CF components and that much has changed with those components since the last Lattice release.

I found the garden-linux binary here `/var/vcap/packages/garden-linux/bin/garden-linux` and see the option to allow `--insecureDockerRegistryList` via `--help`:
```
vagrant@lattice-colocated-0:~$ /var/vcap/packages/garden-linux/bin/garden-linux --help
Usage of /var/vcap/packages/garden-linux/bin/garden-linux:
  -allowHostAccess=false: allow network access to host
  -allowNetworks="": CIDR blocks representing IPs to whitelist
  ...
  -insecureDockerRegistryList="": comma-separated list of docker registries to allow connection to even if they are not secure
```

However, it appears that process is invoked with something else `/usr/local/bin/tee2metron` and I couldn't find much information on how to configure the garden-linux process with the `--insecureDockerRegistryList` option.

I'm aware of the [documentation story on the PivotalTracker!](https://www.pivotaltracker.com/n/projects/1183596/stories/106359650) but was hoping I could get just a few hints that would allow me to figure it out.

Thanks in advance for your help!

**Comment by chadmaughan** [comment]
@davidwadden can you point me in the right direction? Thanks!

**Comment by stanpanza** [comment]
@chadmaughan  I had the same issue , just do vagrant ssh and add the option -insecureDockerRegistry  to  /var/vcap/jobs/garden/bin/garden_ctl , you'll have to search for '/var/vcap/packages/garden-linux/bin/garden-linux'  and it should work
