### ISSUE TITLE
Add support for updating env variables with `ltc update` or `ltc set-env`

### ISSUE THREAD

**Issue by ShawnTuatara** [cloudfoundry-incubator/lattice-release#239]
Using `ltc status my-app` I can see the environment variables that I set during the initial creation of the application. I would like the ability to change those values without requiring the app to be destroyed and recreated. I would think this falls into the same functionality that `cf env` provides.

I am not sure if this is the best overall approach but it is what came most naturally to me right now and the fact that the `cf` CLI has a similar functionality I thought it made sense to request lattice have a similar feature.

**Comment by sclevine** [comment]
Lattice was a Cloud Foundry project focused on delivering the Diego application scheduler into the hands of users as quickly as possible before Diego was fully integrated to Cloud Foundry. Lattice served that purpose well, but now Diego is available as the application scheduler for Cloud Foundry, and Cloud Foundry is the best way to use Diego. Therefore, Lattice is no longer actively maintained.

Apologies for not addressing your issue.

-Stephen
