### ISSUE TITLE
curl: (6) Couldn't resolve host 'receptor.local.lattice.cf' on Windows 10

### ISSUE THREAD

**Issue by amitshukla30** [cloudfoundry-incubator/lattice-release#241]
Trying out Lattice on my windows machine 
I am getting below error. Cannot install the Lattice CLI on windows.

$ curl  http://receptor.local.lattice.cf/v1/sync/windows/ltc.exe
curl: (6) Couldn't resolve host 'receptor.local.lattice.cf'

**Comment by amitshukla30** [comment]
I am using Virtual Box and Vagrant 1.8 latest

**Comment by sclevine** [comment]
Lattice was a Cloud Foundry project focused on delivering the Diego application scheduler into the hands of users as quickly as possible before Diego was fully integrated to Cloud Foundry. Lattice served that purpose well, but now Diego is available as the application scheduler for Cloud Foundry, and Cloud Foundry is the best way to use Diego. Therefore, Lattice is no longer actively maintained.

Apologies for not addressing your issue.

-Stephen
