### ISSUE TITLE
Failed to create container

### ISSUE THREAD

**Issue by n1ko-w1ll** [cloudfoundry-incubator/lattice-release#81]
I have Lattice now up and running with vagrant and setup another vagrant box with ubuntu and installed ltc there. The environment I'm using is as follows:

* HP zBook Windows 7
* 16 GB RAM
* Vagrant 1.6.5
* VirtualBox 4.3.26

If I run
```
ltc target 192.168.11.11.xip.io
ltc create lattice-app cloudfoundry/lattice-app
```
I get the following output:
```
No port specified, image metadata did not contain exposed ports. Defaulting to 8080.
No working directory specified, using working directory from the image metadata...
Monitoring the app on port 8080...
No start command specified, using start command from the image metadata...
Start command is:
/lattice-app
Creating App: lattice-app
.................................08 Apr 10:51 [APP|0] Creating container
08 Apr 10:51 [APP|0] Failed to create container
.......................................................................................
Timed out waiting for the container to come up.
This typically happens because docker layers can take time to download.
Lattice is still downloading your application in the background.
To view logs:
        ltc logs lattice-app
To view status:
        ltc status lattice-app

App will be reachable at:
http://lattice-app.192.168.11.11.xip.io
```
If I run the ltc tests I get the following:
```
Running Suite: Lattice Integration Tests
========================================
Random Seed: 1428491915
Will run 2 of 2 specs

[test] Attempting to stream cluster debug logs
[test] Attempting to create lattice-test-app-0ada13ed-6bcc-49ef-48cf-2ca3294c00b2
[create] Error fetching image metadata: Get https://index.docker.io/v1/repositories/cloudfoundry/lattice-app/images: tls: oversized record received with length 20527
[test] Attempting to remove lattice-test-app-0ada13ed-6bcc-49ef-48cf-2ca3294c00b2
[remove] Error Stopping App: lattice-test-app-0ada13ed-6bcc-49ef-48cf-2ca3294c00b2 is not started. Please start an app first
[test] Polling for the route lattice-test-app-0ada13ed-6bcc-49ef-48cf-2ca3294c00b2.192.168.11.11.xip.io
• Failure [15.139 seconds]
Lattice
/root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/integration_test/integration_test_runner.go:135
  when desiring a docker-based LRP
  /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/integration_test/integration_test_runner.go:134
    eventually runs a docker app [It]
    /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/integration_test/integration_test_runner.go:127

    Got stuck at:
        Error fetching image metadata: Get https://index.docker.io/v1/repositories/cloudfoundry/lattice-app/images: tls: oversized record received with length 20527

    Waiting for:
        lattice-test-app-0ada13ed-6bcc-49ef-48cf-2ca3294c00b2 is now running.

    /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/integration_test/integration_test_runner.go:148
------------------------------
[test] Attempting to create lattice-test-app-66b170fa-4ade-4142-4460-08d029d05b6f
[create] Error fetching image metadata: Get https://index.docker.io/v1/repositories/cloudfoundry/lattice-app/images: tls: oversized record received with length 20527
[test] Attempting to remove lattice-test-app-66b170fa-4ade-4142-4460-08d029d05b6f
[remove] Error Stopping App: lattice-test-app-66b170fa-4ade-4142-4460-08d029d05b6f is not started. Please start an app first
[test] Polling for the route lattice-test-app-66b170fa-4ade-4142-4460-08d029d05b6f.192.168.11.11.xip.io
• Failure [20.162 seconds]
Lattice
/root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/integration_test/integration_test_runner.go:135
  when desiring a docker-based LRP
  /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/integration_test/integration_test_runner.go:134
    eventually runs a docker app with metadata from Docker Hub [It]
    /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/integration_test/integration_test_runner.go:133

    Got stuck at:
        Error fetching image metadata: Get https://index.docker.io/v1/repositories/cloudfoundry/lattice-app/images: tls: oversized record received with length 20527

    Waiting for:
        lattice-test-app-66b170fa-4ade-4142-4460-08d029d05b6f is now running.

    /root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/integration_test/integration_test_runner.go:148
------------------------------


Summarizing 2 Failures:

[Fail] Lattice when desiring a docker-based LRP [It] eventually runs a docker app
/root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/integration_test/integration_test_runner.go:148

[Fail] Lattice when desiring a docker-based LRP [It] eventually runs a docker app with metadata from Docker Hub
/root/go/src/github.com/cloudfoundry-incubator/lattice/ltc/integration_test/integration_test_runner.go:148

Ran 2 of 2 Specs in 35.322 seconds
```
Could it be another problem with our companies proxy server? The proxy was set by vagrant in both boxes in the /etc/environment file and the apt config.

**Comment by LaynePeng** [comment]
Can Docker works inside your company?

**Comment by win1imb** [comment]
I have another Ubuntu VM with docker manually installed where it works. Is there maybe another docker specific proxy setting in addition to the /etc/environment? There is no /etc/default/docker config file on the lattice box.

**Comment by LaynePeng** [comment]
what proxy you set in  /etc/default/docker. Try to add:

```
echo export http_proxy=$PROXY >> /etc/profile
echo export https_proxy=$PROXY >> /etc/profile
```

and restart.

**Comment by win1imb** [comment]
I already set the proxy in /etc/environment. Adding the commands you suggested in the /etc/profile does only overwrite them with the same value.

**Comment by LaynePeng** [comment]
As you said the http_proxy may be rewrited. So can you echo this env in both machines, and see if they are the same.

**Comment by win1imb** [comment]
echo $http_proxy has the same output on all machines (my manually installed docker VM, the lattice vagrant box and the vagrant ubuntu box where ltc is installed).

**Comment by LaynePeng** [comment]
Emm, I am confuse now... Is your company own self certification? "tls: oversized record received with length 20527" seems a certification problem.

**Comment by win1imb** [comment]
I had similar issues in my docker box at the beginning when the proxy setting was not correctly set. I don't know where this error is comming from but we do not own a certification authority.

**Comment by menicosia** [comment]
@LaynePeng @n1ko-w1ll with respect to proxy support, there is now some information in the README.md under the heading, "Proxy configuration."

I am not sure if this helps given the Windows context, but I would like to know if this issue should remain open.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by n1ko-w1ll** [comment]
@menicosia the comments on proxy configuration in general is good, but I already added that lines to my Vagrant file. I tried it one more time with the current v0.2.4 but still no success. Here you can see some lines from the garden-linux-service.log:

```
{"timestamp":"1432018039.063614368","source":"garden-linux","message":"garden-linux.garden-server.bulk_info.got-bulkinfo","log_level":1,"data":{"handles":[""],"session":"4.208"}}
{"timestamp":"1432018039.079877853","source":"garden-linux","message":"garden-linux.pool.nscfdgusdki.creating","log_level":1,"data":{"session":"2.12"}}
{"timestamp":"1432018039.079993963","source":"garden-linux","message":"garden-linux.pool.nscfdgusdki.acquired-pool-resources","log_level":1,"data":{"session":"2.12"}}
{"timestamp":"1432018039.105407476","source":"garden-linux","message":"garden-linux.pool.nscfdgusdki.create-rootfs.failed-to-fetch","log_level":2,"data":{"attempt":1,"error":"Get https://index.docker.io/v1/repositories/cloudfoundry/lattice-app/images: tls: oversized record received with length 20527","of":3,"session":"2.12.1"}}
{"timestamp":"1432018039.115362406","source":"garden-linux","message":"garden-linux.pool.nscfdgusdki.create-rootfs.failed-to-fetch","log_level":2,"data":{"attempt":2,"error":"Get https://index.docker.io/v1/repositories/cloudfoundry/lattice-app/images: tls: oversized record received with length 20527","of":3,"session":"2.12.1"}}
{"timestamp":"1432018039.122423649","source":"garden-linux","message":"garden-linux.pool.nscfdgusdki.create-rootfs.failed-to-fetch","log_level":2,"data":{"attempt":3,"error":"Get https://index.docker.io/v1/repositories/cloudfoundry/lattice-app/images: tls: oversized record received with length 20527","of":3,"session":"2.12.1"}}
{"timestamp":"1432018039.122485399","source":"garden-linux","message":"garden-linux.pool.nscfdgusdki.provide-rootfs-failed","log_level":2,"data":{"error":"Get https://index.docker.io/v1/repositories/cloudfoundry/lattice-app/images: tls: oversized record received with length 20527","session":"2.12"}}
{"timestamp":"1432018039.122508526","source":"garden-linux","message":"garden-linux.garden-server.create.failed","log_level":2,"data":{"error":"Get https://index.docker.io/v1/repositories/cloudfoundry/lattice-app/images: tls: oversized record received with length 20527","request":{"handle":"lattice-app-0d0cf181-8e68-4802-68c7-b4acb7e2f228","rootfs":"docker:///cloudfoundry/lattice-app#latest","properties":{"executor:action":"{\"run\":{\"path\":\"/lattice-app\",\"args\":[],\"dir\":\"/\",\"env\":null,\"resource_limits\":{}}}","executor:allocated-at":"1432018039066389177","executor:cpu-weight":"100","executor:disk-mb":"1024","executor:egress-rules":"null","executor:env":"[{\"name\":\"INSTANCE_GUID\",\"value\":\"0d0cf181-8e68-4802-68c7-b4acb7e2f228\"},{\"name\":\"INSTANCE_INDEX\",\"value\":\"0\"},{\"name\":\"PROCESS_GUID\",\"value\":\"lattice-app\"},{\"name\":\"PORT\",\"value\":\"8080\"}]","executor:log-config":"{\"guid\":\"lattice-app\",\"index\":0,\"source_name\":\"APP\"}","executor:memory-mb":"128","executor:metrics-config":"{\"guid\":\"lattice-app\",\"index\":0}","executor:monitor":"{\"run\":{\"path\":\"/tmp/healthcheck\",\"args\":[\"-port\",\"8080\"],\"env\":null,\"resource_limits\":{},\"log_source\":\"HEALTH\"}}","executor:owner":"executor","executor:result":"{\"failed\":false,\"failure_reason\":\"\",\"stopped\":false}","executor:rootfs":"docker:///cloudfoundry/lattice-app#latest","executor:setup":"{\"download\":{\"from\":\"http://file_server.service.dc1.consul:8080/v1/static/healthcheck.tgz\",\"to\":\"/tmp\",\"cache_key\":\"\"}}","executor:start-timeout":"0","executor:state":"created","tag:domain":"lattice","tag:instance-guid":"0d0cf181-8e68-4802-68c7-b4acb7e2f228","tag:lifecycle":"lrp","tag:process-guid":"lattice-app","tag:process-index":"0"},"env":["INSTANCE_GUID=0d0cf181-8e68-4802-68c7-b4acb7e2f228","INSTANCE_INDEX=0","PROCESS_GUID=lattice-app","PORT=8080"],"privileged":true},"session":"4.209"}}
{"timestamp":"1432018039.132901907","source":"garden-linux","message":"garden-linux.garden-server.destroy.failed","log_level":2,"data":{"error":"unknown handle: lattice-app-0d0cf181-8e68-4802-68c7-b4acb7e2f228","handle":"lattice-app-0d0cf181-8e68-4802-68c7-b4acb7e2f228","session":"4.210"}}
{"timestamp":"1432018058.974041700","source":"garden-linux","message":"garden-linux.garden-server.bulk_info.got-bulkinfo","log_level":1,"data":{"handles":[""],"session":"4.215"}}
{"timestamp":"1432018058.975141287","source":"garden-linux","message":"garden-linux.garden-server.bulk_metrics.got-bulkinfo","log_level":1,"data":{"handles":[""],"session":"4.216"}}
```
The error
```
tls: oversized record received with length 20527
```
is still there :(

**Comment by LaynePeng** [comment]
Hi, all,

I found this issue may happen in new docker-registry.

**Comment by menicosia** [comment]
Hi @LaynePeng, @n1ko-w1ll,

As you guys know, although this is an Open Source (and therefore, community) project. We're really happy to see consistent interest in Windows! At Pivotal, we haven't gotten to start working on Windows support. I don't think there's a lot we can do about this until then. Right now, we can't even set up an environment to replicate your problems.

So I'm going to leave this GitHub issue open, here on the community project, and take the story that's in the Open Source tracker [[#92027272](https://www.pivotaltracker.com/story/show/92027272)], and align it with the Windows track we have planned.

If you guys haven't been able to sort out problems such as this by then, we should be able to take a look at that time.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by stemau98** [comment]
Hi! I' ve tested the new version of lattice 0.5.0 with vagrant on my laptop. At first everything seems to be good, but when I do ltc test, I get following error message: Error fetching image metadata: Get https://index.docker.io/v1/repositories/cloudfoundry/lattice-app/images: tls: oversized record received with length 20527

I think it have something to do with proxy settings because first time I set up docker I have the same problem. After I set the http_proxy in docker settings the problem was solved.
I 've check already the proxy settings in /var/lattice/setup/lattice-environment and it seems fine.

So are there any other proxy settings inside lattice???

**Comment by davidwadden** [comment]
@stemau98 

are you following our [proxy setup](http://lattice.cf/docs/proxy/) instructions?

what is the output if you run `env | grep -i proxy` ?  
  - this is the `ltc` proxy 
what is output from `curl http://$(ltc target -d):8444/proxyconf.json` 
  - this is the cluster proxy (based on proxy vars at provision-time [`vagrant up`])

as explained on the doc, there are two proxy configurations: cluster to internet and CLI to cluster+internet, the former is based on content of `http_proxy` `https_proxy` and `no_proxy` at the time you `vagrant up`, the latter is the content of those environment variables when running `ltc` commands.

please open a new issue if you continue to have problems

**Comment by davidwadden** [comment]
@n1ko-w1ll we're still working towards supporting "windows as a user" functionality.  your specific issue should be addressed with [[#98709384](https://www.pivotaltracker.com/story/show/98709384)] , but keep  an eye on [[##2084998](https://www.pivotaltracker.com/epic/show/2084998)] for windows `ltc`

**Comment by n1ko-w1ll** [comment]
@davidwadden thanks for the links. I haven't looked at lattice since I had this issue. At the moment we're working with docker, which works more or less, but production environment is CF... thus a local lattice environment to test before pushing to CF would be awesome.

**Comment by davidwadden** [comment]
We're currently looking into ways we can provide an experience more like `cf push` on Lattice.

Do you mind giving me an idea of what you'd like Lattice to provide in a "test environment before `cf push` to prod CF install" ?

Examples:
- docker images vs buildpack-created droplets
  - care about pushing same bits from "test" lattice droplet to "prod" cf droplet
- service bindings
  - what services do you bind to in CF?  
  - where would you want them to bind to?
    - ephemeral db running in docker image
    - user-provided service (db on lan, db on cloud)
  - manifest support

Also, `vagrant up` works on Windows as of our latest [nightly bundle](https://lattice.s3.amazonaws.com/nightly/index.html), except one issue #226 that prevents downloading the `lattice.tgz` behind a proxy (there's a [workaround](https://github.com/cloudfoundry-incubator/lattice-release/issues/226#issuecomment-152393075) to download the `lattice.tgz` manually).

**Comment by n1ko-w1ll** [comment]
We would like to be able to integration test our services before pushing them to CF. That means we want to link the services against provided services in CF like MongoDB and RabbitMQ (maybe others later) as well as link custom services against each other to test the correct routing and communication between them.

For example, we have an API gateway that authenticates the user and forwards the request to the right service. The gateway has to know the routes to the individual services which are given via user provided services at the moment. Additionally the gateway calculates a signature for every request, to prevent internal attacks (CF internal routes are not secured).

When we do our tests with docker, we have to simulate some behavior from CF which is not always how CF behaves in the end. For example which environment variables are given to the application.

Another issue we had in the past was with appdynamics, which replaced the standard java buildpack with one that was handling java 8 lambdas wrong and broke our service on CF.

For such reasons it would be nice to have a local environment that is much more like the production environment than just using docker.

**Comment by sophokles73** [comment]
I am running into the same problem as pointed out by @n1ko-w1ll running on lattice-0.6.0 on a company network behind a proxy :-(

I have set up the proxy URLs as described in [Proxy Setup](http://lattice.cf/docs/proxy/). However, when I try to

```
ltc create mosquitto ansi/mosquitto
```
I get the following:
```
Warning: No container user specified to run your app, your app will be run as root!
No port specified, using exposed ports from the image metadata.
        Exposed Ports: 1883
No working directory specified, using working directory from the image metadata...
Working directory is:
/usr/local/src/mosquitto-1.4
Monitoring the app on port 1883...
No start command specified, using start command from the image metadata...
Start command is:
/usr/local/sbin/mosquitto
Creating App: mosquitto
.11/11 08:47:54.27 [APP|0] Failed to create container
11/11 08:47:54.32 [APP|0] Creating container
11/11 08:47:54.35 [APP|0] Failed to create container
11/11 08:47:54.38 [APP|0] Creating container
11/11 08:47:54.40 [APP|0] Failed to create container
..........................................................11/11 08:48:53.10 [APP|0] Creating container
11/11 08:48:53.13 [APP|0] Failed to create container
............................................................
Timed out waiting for the container to come up.
This typically happens because docker layers can take time to download.
Lattice is still downloading your application in the background.
To view logs:
        ltc logs mosquitto
To view status:
        ltc status mosquitto

App will be reachable at:
http://mosquitto.local.lattice.cf
http://mosquitto-1883.local.lattice.cf
```

The garden log at `/var/vcap/sys/log/garden/garden.stdout.log` contains
```
{"timestamp":"1447228223.289445639","source":"garden-linux","message":"garden-linux.pool.5cm5h38soa0.provide-rootfs-failed","log_level":2,"data":{"error":"repository_fetcher: GetRepositoryData: could not fetch image ansi/mosquitto from registry index.docker.io: Get https://index.docker.io/v1/repositories/ansi/mosquitto/images: tls: oversized record received with length 20527","session":"5.5"}}
{"timestamp":"1447228223.289960146","source":"garden-linux","message":"garden-linux.garden-server.create.failed","log_level":2,"data":{"error":"repository_fetcher: GetRepositoryData: could not fetch image ansi/mosquitto from registry index.docker.io: Get https://index.docker.io/v1/repositories/ansi/mosquitto/images: tls: oversized record received with length 20527","request":{"Handle":"mosquitto-478d7b8f-371e-4b10-5a99-58a5fa3f6e42","GraceTime":0,"RootFSPath":"docker:///ansi/mosquitto#latest","BindMounts":null,"Network":"","Privileged":false,"Limits":{"bandwidth_limits":{},"cpu_limits":{"limit_in_shares":1024},"disk_limits":{"inode_hard":200000},"memory_limits":{"limit_in_bytes":134217728}}},"session":"8.149"}}
```

which indicates to me that the garden process does not use the configured proxy when trying to retrieve the image from Docker Hub.

However, when I run
`curl https://index.docker.io/v1/repositories/ansi/mosquitto/images`
from a shell on the lattice VM I get the expected response from Docker Hub:
```
[{"checksum": "", "id": "fb08298a9c8e9077922f5bf2c7c86fa6d897b5414da9930126195171cac3b295"}, {"checksum": "", "id": "911f3f4677dc08c7837549da849d3b758c3d5b7e111e8a2490c5ef85ffe39538"}, {"checksum": "", "id": "626b77743a403cdc0788efb61abab768eb18cfe874c3a3dac4c7ff08ecd16ec1"}, {"checksum": "", "id": "ddef7853400ea267d1fc233b3b4bb9dbb4d947deea58a421772b8871bc97a486"}, {"checksum": "", "id": "59c1facfeb5a822b0d88cbfc633a8d7e88f030961ff79a6cb5ff44013b74fa5e"}, {"checksum": "", "id": "2c93ec07ad5f8ac1e64a9b75f3580f1e594e2a593c8dd2d218107ad3247efcc3"}, {"checksum": "", "id": "d71404b231b70b41337e34bf833ffa6eef106b65c45462cb911cace60fa2ccae"}, {"checksum": "", "id": "d87ec76571b30e6305fae2621e76119f4ff8f473c1c7a50874bccc49b21e395e"}, {"checksum": "", "id": "f09b555c50a23198be1e6fa392cf41b03ef9128253233d499f0d03b7bab38f2e"}, {"checksum": "", "id": "b7cf8f0d9e82c9d96bd7afd22c600bfdb86b8d66c50d29164e5ad2fb02f7187b"}, {"checksum": "", "id": "2c014f14d3d95811df672ddae2af376f9557f6b8f5623e3e3f8c5ca3f6ff42e6"}, {"checksum": "", "id": "a62a42e77c9c3626118dc411092d23cf658220261acdafe21a7589a8eeba627e"}, {"checksum": "", "id": "706766fe101906a1a6628173c2677173a5f8c6c469075083f3cf3a8f5e5eb367"}, {"checksum": "", "id": "bd05a65956e2c522bb7aa60d81ea6d1e2e7eb5b6179724e07db9dba738804b56"}, {"checksum": "", "id": "36a7fb64070015e9052ce8b3a9df92755428e50a586e487a80e5c649a59fc722"},
.....
````

Any ideas how to solve this problem? We would love to be able to use lattice for the same reasons @n1ko-w1ll pointed out above ....

**Comment by mbechauf** [comment]
I think I know what the problem is with running Lattice behind a proxy, and I think it's neither a Windows nor a Vagrant problem. What I did is write a little test program that would create a container through the Garden client API. I first did the test with a local container filesystem, and when that worked, I tried to launch a Docker container. The result is that even through the Garden client library the Docker images cannot be pulled from the Docker repository, even though the `HTTP_PROXY` and `HTTPS_PROXY` variables were set on the command line. The Garden client test program is below. 

This meant that the problem could only be related to the way that Garden Linux is launched and what environment variables were set in the init process. I figured out that it is launched through the `monit` daemon, which is started with `/var/vcap/bosh/bin/monit -I -c /var/vcap/bosh/etc/monitrc`. The `monitrc` file then points to `/var/vcap/monit/job/0012_garden.monitrc` and then to `/var/vcap/jobs/garden/bin/garden_ctl'. 

In the Garden Linux startup script `garden_ctl`, I did a quick hack and inserted our proxy addresses manually

```
    echo $$ > $PIDFILE

#  -------------- INSERT ---------------
    export HTTP_PROXY=http://proxy.pal.sap.corp:8080 
    export HTTPS_PROXY=http://proxy.pal.sap.corp:8080 
#  -------------- END INSERT ---------------

    exec /usr/local/bin/tee2metron -dropsondeDestination=127.0.0.1:3457 -sourceInstance=latticecolocated-0 /var/vcap/packages/garden-linux/bin/garden-linux -externalIP=192.168.11.11 \
      -depot=/var/vcap/data/garden/depot \
      -snapshots="${snapshots_path}" \
      -graph=$graph_path \
      -bin=/var/vcap/packages/garden-linux/src/github.com/cloudfoundry-incubator/gardenlinux/linux_backend/bin \
      -mtu=1500 \
      -listenNetwork=unix \
      -listenAddr=/var/vcap/data/garden/garden.sock \
      -denyNetworks= \
      -allowNetworks= \
      -allowHostAccess=true \
      -networkPool=10.254.0.0/22 \
      -debugAddr=0.0.0.0:17013 \
      -rootfs=/var/vcap/packages/busybox \
      -containerGraceTime=5m \
```

and then restarted Garden Linux with `monit restart garden`. I ran my Garden client test program again, and this time it immediately worked. Then I tried `ltc create lattice-app cloudfoundry/lattice-app`, and after a short time pulling the Docker base image, the app launched without a glitch.

Problem found - but it obviously needs to be solved in a cleaner way. For sure, the current way that the proxy setup is described in the Lattice documentation through Vagrant is not sufficient.

This is the Garden client API test program I used:
```
package main

import (
        "fmt"
        "bytes"
        "os"
        "github.com/cloudfoundry-incubator/garden"
        "github.com/cloudfoundry-incubator/garden/client"
        "github.com/cloudfoundry-incubator/garden/client/connection"
)


func main() {

        fmt.Println("Start")

        fmt.Println("Acquiring connection ...")
        gardenClient := client.New(connection.New("unix", "/var/vcap/data/garden/garden.sock"))
        if gardenClient == nil {
                fmt.Println("Error acquiring client connection")
                os.Exit(1)
        }
        fmt.Println("Success!")

        fmt.Println("Creating container ...")
        container, error := gardenClient.Create(garden.ContainerSpec{})
        if container == nil {
                fmt.Printf("Error creating the container, error=%s\n",error)
                os.Exit(1)
        }
        fmt.Println("Success!")

        fmt.Println("Creating Docker container ...")
        dockerContainer, error := gardenClient.Create(garden.ContainerSpec{
                RootFSPath: "docker:/busybox"})
        if dockerContainer == nil {
                fmt.Printf("Error creating the Docker container, error=%s\n",error)
                os.Exit(1)
        }
        fmt.Println("Success!")

        buffer := &bytes.Buffer{}
        if buffer == nil {
                fmt.Println("Error")
                os.Exit(1)
        }


        fmt.Println("Trying to run the container\n")
        process, _ := dockerContainer.Run(garden.ProcessSpec{
          User: "default",
          Path: "echo",
          Args: []string{"hello from the container"},
        }, garden.ProcessIO{
          Stdout: buffer,
          Stderr: buffer,
        })

        fmt.Println("Success ... and now waiting for result!")
        process.Wait()
        fmt.Println(buffer.String())

}
```

**Comment by sclevine** [comment]
Lattice was a Cloud Foundry project focused on delivering the Diego application scheduler into the hands of users as quickly as possible before Diego was fully integrated to Cloud Foundry. Lattice served that purpose well, but now Diego is available as the application scheduler for Cloud Foundry, and Cloud Foundry is the best way to use Diego. Therefore, Lattice is no longer actively maintained.

Apologies for not continuing to address this issue.

-Stephen
